### PR TITLE
feat: New Service Call - Start Climate Control

### PR DESCRIPTION
**Pull request by coreywillwhat**
### New Service Call - Start Climate Control
`audiconnect.start_climate_control`
Optional inputs for:
- Target Temperature (Fahrenheit)
- Target Temperature (Celsius)
- Glass Surface Heating
- Auto Seat Comfort
    - Front Left
    - Front Right
    - Rear Left
    - Rear Right

### services.yaml
- fixed a bug where refresh_vehicle_data was not pointing to the right service.
- Improvements to front end service call interface
- added new service call

### readme.md
- small improvements
- added new service call info

### Notes
By preserving the legacy set_climatisation function, we both avoid breaking changes in existing configurations, and keep the `execute_vehicle_action` service simple.

### CODE REVIEW

**Comment by Kolbi** [comment]
Thanks for the work. Looks good although I already created a PR with some changes to the services: https://github.com/audiconnect/audi_connect_ha/pull/287 but I wouldn't be an issue to adapt my PR to your changes

I have two questions in my mind:
* make it more flexible even for stopClimatisation see: https://github.com/audiconnect/audi_connect_ha/discussions/282#discussioncomment-8764481 ?
* does my car also have the options for MirrorHeating and zoneSetting :D

**Comment by coreywillwhat** [comment]
I saw your PR with the service changes after I'd completed of course haha as you mentioned, I figure we can adapt mine to fit once yours is pulled. I'd like to get the vehicle drop downs you added in the service calls first, then we could include my new service call with adjustments. The changes to mine should be fairly small once yours are in.

Hadn't seen @t0bias-r discussion post yet. Massively helpful. Thanks for pointing me to it.

What are you thinking to make stopClimatisation more flexible? Lets move this to a feature request issue if you want to discuss more. Don't want to clog this up too much.

The options available should be in your Audi app for your vehicle. When i open "start climate control" in the app, i see target temperature, Glass Surface Heating, and Auto Seat Comfort (for the front two seats), which are all sent with the start climate controls service.

**Comment by coreywillwhat** [comment]
Closing as merged into #311

**Comment by coreywillwhat** [comment]
Closing as merged into #311

**Pull request closed without merging**
