### PR TITLE
fix: Any Window Open w/ Unsupported Sunroof

### PR DESCRIPTION
**Pull request by coreywillwhat**
Allows for unsupported window state for the sunRoof.
I haven't had a chance to test this yet with my car. I will do that later today.
@Kolbi if you get a chance to test on yours that would be great.

### CODE REVIEW

**Comment by Kolbi** [comment]
Seems not to work.

**Comment by coreywillwhat** [comment]
ah okay, right, we can default to None then I think

**Comment by coreywillwhat** [comment]
give it a shot now if you don't mind. I have to jump on some calls. If that doesn't work, I can work on it in a few hours.

**Comment by coreywillwhat** [comment]
Tested and the updated code is still working for me.

**Comment by cdnninja** [comment]
> give it a shot again if you have a chance. I have to jump on some calls. If that doesn't work, I can test/work on it in a few hours.

I will leave this one for @Kolbi  to review and merge.

**Comment by Kolbi** [comment]
Tested and working :) Thanks @coreywillwhat

**Pull request merged**
