### PR TITLE
feat: add device tracker debug log

### PR DESCRIPTION
**Pull request by Kolbi**
In order to analyse https://github.com/audiconnect/audi_connect_ha/issues/307 I added the possibility to provide debug logs for device_tracker

### CODE REVIEW

**Comment by coreywillwhat** [comment]
Users might be concerned with privacy of sharing location. Suggest we redact in the logs....although, maybe thats part of the puzzle.
```python

import re

            #Redacted Log
            resp_redacted = resp.copy()
            resp_redacted["data"]["lon"] = re.sub(r'\d', '#', str(resp["data"]["lon"]))
            resp_redacted["data"]["lat"] = re.sub(r'\d', '#', str(resp["data"]["lat"]))
            _LOGGER.debug(f"update_vehicle_position: {resp_redacted}")
```
here is the result:
`2024-04-10 06:00:31.010 DEBUG (MainThread) [custom_components.audiconnect.audi_connect_account] update_vehicle_position: {'data': {'lon': '-###.######', 'lat': '##.######', 'carCapturedTimestamp': datetime.datetime(2024, 4, 9, 23, 11, 27, tzinfo=datetime.timezone.utc)}}`

**Comment by coreywillwhat** [comment]
with the redacted log, the device_tracker is failing...I'm not sure why.

**Comment by coreywillwhat** [comment]
Added more logs and redacted vin/lat/lon. Hopefully get to the bottom of this issue.

**Comment by Kolbi** [comment]
Change LOGGER.info to LOGGER.debug according to: https://developers.home-assistant.io/docs/development_guidelines/?_highlight=log#log-messages ?

**Pull request merged**
