### PR TITLE
feat: Enhanced Logging for _tryAppendStateWithTs and _tryAppendFieldWithTs

### PR DESCRIPTION
**Pull request by coreywillwhat**
This should help both devs and users being able to read the logs to understand when sensor values are found and appended, or not.
Q4 and e-tron owners are having issues seeing sensors, so this is the first piece to figuring that out.

### CODE REVIEW

**Comment by Kolbi** [comment]
Regaring "Also note that _LOGGER.info is reserved for the core, use _LOGGER.debug for anything else."
https://developers.home-assistant.io/docs/development_guidelines/?_highlight=log#log-messages

I changed LOGGER.info => LOGGER.debug

**Comment by coreywillwhat** [comment]
Oh yeah great catch/find. Would be nice to use the .info level for higher level logging, but since we can't, I've removed some lines which don't feel useful anymore.

**Comment by coreywillwhat** [comment]
removed f-strings from logging as well, as said in documentation.
ready for review.

**Review by Kolbi — APPROVED** [review]
looks good for me

**Pull request merged**
