### PR TITLE
feat: New Services, Device Drop Downs, Scan Interval Update

### PR DESCRIPTION
**Pull request by coreywillwhat**
## New Features

All credit goes to @Kolbi with this PR https://github.com/audiconnect/audi_connect_ha/pull/287 for linking devices to vins for drop downs.

### Enhanced Service Calls
- Service calls now feature drop-down menus for the `vin` parameter, allowing users to easily select the target vehicle directly from the UI.

#### Duplicate Entity Issue
- Upgrading to this version may result in the creation of a duplicate entity. This entity will not contain any data except for the area assignment from its predecessor. The impact of deleting this duplicate entity has not been fully evaluated.

#### Solution for Duplicate Entity
- To eliminate the duplicate entity, follow these steps:
  - Delete the AudiConnect integration from Home Assistant.
  - Restart Home Assistant.
  - Re-add the integration.

### Configure Scan Interval From Front End
- Allows the user to `configure` the scan interval from the front end through options flow.

### `audiconnect.refresh_cloud_data`

Introduces the `audiconnect.refresh_cloud_data` service call. The service leverages an existing backend function, now made accessible through the Home Assistant UI. It's designed to update vehicle data from an online source for all vehicles linked to an account without initiating a vehicle-side refresh.

### Use Case:
Given some limitations with the "Refresh Vehicle Data" functionality, this service call provides a workaround by allowing users to manually trigger data updates. It's particularly useful for users who prefer to extend the default refresh interval significantly and wish to manually request updates at specific moments, such as after starting climate control or during periods of inactivity.

### Service Call Description:

- Functionality: Updates data for all vehicles from the online source, mirroring the action performed at integration startup or during scheduled refresh intervals.
- Behavior: Does not force a vehicle-side data refresh. Consequently, if vehicles haven't recently pushed updates, retrieved data might be outdated.
- Recommended Usage: Ideal for post-command updates (e.g., after initiating climate control). To ensure data accuracy, a delay of approximately 30 seconds is recommended between command issuance and this service call.
- Note: This service essentially replicates the function of restarting the integration, offering a more granular control over data refresh moments.

This addition aims to enhance user control over data updates, addressing specific scenarios where updated information is crucial without unnecessarily frequent automated refreshes.

### `audiconnect.start_climate_control`

Optional inputs for:

- Target Temperature (Fahrenheit)
- Target Temperature (Celsius)
- Glass Surface Heating
- Auto Seat Comfort
  - Front Left
  - Front Right
  - Rear Left
  - Rear Right

_Note; These functions directly relate to the Audi App "Climate Control" settings for Target Temperature, Glass Surface Heating, and Auto Seat Comfort._

### services.yaml

- fixed a bug where refresh_vehicle_data was not pointing to the right service.
- Improvements to front end service call interface
- added new service call

### readme.md

- small improvements
- added new service call info

### Notes

By preserving the legacy set_climatisation function, we both avoid breaking changes in existing configurations, and keep the `audiconnect.execute_vehicle_action` service simple.

### CODE REVIEW

**Comment by coreywillwhat** [comment]
@Kolbi turns out I made a bit of a mess on my fork. Cleaned up and put in one PR. I included all of your lines exactly other than the `translations` which are not included.

**Comment by cdnninja** [comment]
Would this be instead of #287? This is alot changing in a PR.

**Comment by coreywillwhat** [comment]
Yeah, I apologize for that, I ended up having an excessive amount of time to get this done in the last 48 hours.

The separate features and fixes were getting too much to maintain/develop separately so I merged them into my master branch/fork and just combined them all.

This does include #287 .

No hard feeling if you want to reject it/don't have the time to do it all in one go.

I won't have as much time in the coming days/months with the baby coming soon, but I'm happy to break it down into bite size pieces when I have time.

**Comment by coreywillwhat** [comment]
found a bug with the scan interval options. Will resubmit all of these features separately like i should have done in the first place.

**Pull request closed without merging**
