### PR TITLE
style: Update audi_models.py

### PR DESCRIPTION
**Pull request by Ingrimmsch93**
removed unnecessary comma and streamlined formatting

### CODE REVIEW

**Comment by Kolbi** [comment]
mmh Pre-Commit recently added them... https://github.com/Kolbi/audi_connect_ha/commit/7fda643bdb9d99deb243acdbcb2b6eb633a61b30#diff-decdc50a875cd0173e621453749b6838d5611866684bda843a9194cb7717732d

**Comment by Ingrimmsch93** [comment]
This precommit was done by a bot, right?
I don't get why some lines stayed in one line without extra comma and other where split over multiple lines with extra comma.
I am not experienced enough to tell if it could be a problem.

**Comment by Kolbi** [comment]
Yes a bot.

Funny thing: https://github.com/arjenvrh/audi_connect_ha/pull/269/commits/9f56ba34b726b5acf28cdf6fd848280b61518e50 to be honest I currently don't know why some fields are formatted in multiple lines and some in a single line... maybe because of the length.

**Comment by cdnninja** [comment]
Most likely a length thing.

**Comment by cdnninja** [comment]
Now that the pre-commit is working looks like this can be closed as it un does ruff.

**Pull request closed without merging**
