### PR TITLE
fix: Patch sun roof

### PR DESCRIPTION
**Pull request by Kolbi**
Add entity sun_roof Open & Closed currently we only have closed in HA

fix https://github.com/audiconnect/audi_connect_ha/issues/352

### CODE REVIEW

**Comment by coreywillwhat** [comment]
should be able to test existing vs this today.

**Comment by cdnninja** [comment]
Oops missed that comment.   Let me know if I need to revert the merge.

**Comment by coreywillwhat** [comment]
I'll let you know. I know from going through all the old issues, and closing them out, there is some code somewhere that accounts for the window/door not being available. So I wasn't sure if that was also something we needed to look into/account for as well.

**Comment by coreywillwhat** [comment]
Sure enough, when the sunroof is open it reports as `unknown`
This patch fixes it. Thanks for this!

**Comment by coreywillwhat** [comment]
spoke too soon. I think its always reporting `Open` now

**Comment by coreywillwhat** [comment]
i've got it, i'll submit another PR

**Pull request merged**
